INSERT INTO ADRESSE (plz, ort, strasse, hausnr) VALUES ('49076', 'Osnabrueck', 'Strasse1', '1');
INSERT INTO ADRESSE (plz, ort, strasse, hausnr) VALUES ('48149', 'Muenster', 'Strasse2', '2');
INSERT INTO ADRESSE (plz, ort, strasse, hausnr) VALUES ('10115', 'Berlin', 'Strasse3', '3');
INSERT INTO ADRESSE (plz, ort, strasse, hausnr) VALUES ('20095', 'Hamburg', 'Strasse4', '4');
INSERT INTO ADRESSE (plz, ort, strasse, hausnr) VALUES ('50667', 'Koeln', 'Strasse5', '5');
INSERT INTO ADRESSE (plz, ort, strasse, hausnr) VALUES ('60311', 'Frankfurt', 'Strasse6', '6');
INSERT INTO ADRESSE (plz, ort, strasse, hausnr) VALUES ('70173', 'Stuttgart', 'Strasse7', '7');
INSERT INTO ADRESSE (plz, ort, strasse, hausnr) VALUES ('80331', 'Muenchen', 'Strasse8', '8');
INSERT INTO ADRESSE (plz, ort, strasse, hausnr) VALUES ('90402', 'Nuernberg', 'Strasse9', '9');
INSERT INTO ADRESSE (plz, ort, strasse, hausnr) VALUES ('01067', 'Dresden', 'Strasse10', '10');

INSERT INTO KUNDE (name, adresse_id) VALUES ('Hans A. Plast', 1);
INSERT INTO KUNDE (name, adresse_id) VALUES ('Anna B. Muster', 2);
INSERT INTO KUNDE (name, adresse_id) VALUES ('Peter C. Lustig', 3);
INSERT INTO KUNDE (name, adresse_id) VALUES ('Clara D. Himmel', 4);
INSERT INTO KUNDE (name, adresse_id) VALUES ('Max E. Mustermann', 5);
INSERT INTO KUNDE (name, adresse_id) VALUES ('Julia F. Beispiel', 6);
INSERT INTO KUNDE (name, adresse_id) VALUES ('Tom G. Test', 7);
INSERT INTO KUNDE (name, adresse_id) VALUES ('Laura H. Demo', 8);
INSERT INTO KUNDE (name, adresse_id) VALUES ('Mark I. Probe', 9);
INSERT INTO KUNDE (name, adresse_id) VALUES ('Nina J. Versuch', 10);